version: "3.9"

services:
  fastapi-app:
    build: .
    ports:
      - "8010:8000"  # Exposes port 8000 for the FastAPI app
    volumes:
      - .:/app           # Mounts the current directory to the container's /app folder
      - ./db:/app/db     # Mounts the local db directory to persist SQLite data
    environment:
      - PYTHONUNBUFFERED=1
